$(document).ready(function()
{
    $("#akh,#hes,#mkh,#tkh,#sst,#arz,#shz,#shh,#kh,#na,#man,#hk").mouseenter(function()
    {
        $(this).fadeTo(700,1);
    });
    $("#akh,#hes,#mkh,#tkh,#sst,#arz,#shz,#shh,#kh,#na,#man,#hk").mouseleave(function()
    {
        $(this).fadeTo(700,0.9);
    });
});
